In [2]:
d = {'a':10,'z':1}


In [6]:
#zipping two list together
x = [11,12,13]
y = [21,22,23]
print(list(zip(x,y)))
# cartesian product
# when list size is different
z = [14,15,16,17]
print(list(zip(x,z)))
# one to one mapping

[(11, 21), (12, 22), (13, 23)]
[(11, 14), (12, 15), (13, 16)]


In [35]:
import re
a = 'eshita gangwar' 

l = re.findall('[a-zA-Z]',a)
d = {'a':'1','e':'2','i':'3','o':'4','u':'5'}
for i in range(len(l)):
    if l[i] in d.keys():
        k = l[i]
        l[i]=d[str(k)]
print("".join(l))
for i in l:
    print(i,end=" ")

2sh3t1g1ngw1r
2 s h 3 t 1 g 1 n g w 1 r 

In [34]:
# v.get(char , char)
# where it will be mapping the dict keys to the value of the dict
# join every value list

In [41]:
a = 'eshita gangwar is a good girl'
d = {'a':'1','e':'2','i':'3','o':'4','u':'5'}
a = a.split()
for q in a:
    k =''
    l = re.findall('[a-zA-Z]',q)
    for i in range(len(l)):
        if l[i] in d.keys():
            k = l[i]
            l[i]=d[str(k)]
    print("".join(l) , " " , end =" ")
    
    
    
    

2sh3t1   g1ngw1r   3s   1   g44d   g3rl   

# Numpy

# numpy -> numerical python
Helps me perform vectorized operations for a analytics
1. adding element to a vector
2. multiplying elements of a vector
3. conditional subsetting
4. get summary statistics like , min, max , mean , 

In [1]:
x = [10,20,30,40,50]
# What are the difference ways in which u can
# multiply every element of the list by 10
# Method 1 : Use map and lambda
print(list(map(lambda i : i*10 , x)))
# Method 2 : 
print([i*10 for i  in x])


[100, 200, 300, 400, 500]
[100, 200, 300, 400, 500]


In [2]:
import numpy as np

In [3]:
nparray = np.array(x)
type(nparray)
# list as the arguement

numpy.ndarray

In [4]:
print(nparray+10)
# list is hetrogenous

[20 30 40 50 60]


In [6]:
x = [10,20,'hello', 'h',2.5]
n = np.array(x)
print(n)
# homogenous is array


['10' '20' 'hello' 'h' '2.5']


In [8]:
#indexing of two types
# positional 
print(n[1])
# conditional
print(n[0:4])

20
['10' '20' 'hello' 'h']


In [10]:
x = [10,20,30,40,50]
n1 = np.array(x)
print(n1>30)
q = n1>30
# boolean list
print(n1[q])

[False False False  True  True]
[40 50]


In [14]:
print(n1)
print('sum' , n1.sum())
print('mean' , n1.mean())
print('min' , n1.min())
print('max' , n1.max())
print('mean' , n1.mean())
print('std' , n1.std())
print('var' , n1.var())
print('argument max' , n1.argmax())
print('argument min ' , n1.argmin())
np.median(n1)

[10 20 30 40 50]
sum 150
mean 30.0
min 10
max 50
mean 30.0
std 14.142135623730951
var 200.0
argument max 4
argument min  0


30.0

In [15]:
num = np.array([[1,2,3],[4,5,6]])
num.shape

(2, 3)

In [95]:
num1 = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(num1)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [96]:
num1.shape

(2, 2, 3)

In [98]:
num1[1][1][1]

11

In [102]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [103]:
np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [106]:
np.ones((5,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [107]:
# subtract every element of npx by 2
# multiply every element of npx by 

In [116]:
npx = np.array([[1,2,3],[4,5,6]])
#print(npx)
#print(npx-2)
#print(npx*npx)
#print(npx[1]*npx[0])
print(npx-npx.mean())

[[-2.5 -1.5 -0.5]
 [ 0.5  1.5  2.5]]


In [129]:
print(type(range(0,4)))
print(list(range(0,4)))
print(range(0,4))
l = range(1,100)
print(list(l))

<class 'range'>
[0, 1, 2, 3]
range(0, 4)
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99]


In [140]:
x = np.arange(10)# array of the range starting from 0 to 10
print(type(x))
print(x)

<class 'numpy.ndarray'>
[0 1 2 3 4 5 6 7 8 9]


In [141]:
x.reshape((5,2))

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [150]:
x.reshape((1,10))

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [174]:

x1 = x.reshape((1,10))
x1

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [164]:
x1.flatten()
# one dimensional array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [172]:
x2 = np.arange(10)
x3 = x2.reshape(1,10)
print(x2)
print(x3)
print(type(x3.flatten()))
print(x3.flatten())
x3.flatten()

[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4 5 6 7 8 9]]
<class 'numpy.ndarray'>
[0 1 2 3 4 5 6 7 8 9]


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [188]:
e = np.arange(12)
e.reshape((6,2,1))
#reshape((d, row, col))

array([[[ 0],
        [ 1]],

       [[ 2],
        [ 3]],

       [[ 4],
        [ 5]],

       [[ 6],
        [ 7]],

       [[ 8],
        [ 9]],

       [[10],
        [11]]])

In [16]:
np1 = np.array([[1,2,3],[4,5,6]])
np2 = np.array([[7,8,9],[10,11,12]])
np3 = np.array([[13,14,15,16],[17,18,19,20]])
np.concatenate([np1,np2],axis =0) # rbind

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [202]:
np.vstack((np1,np2))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [205]:
print(np.concatenate([np1,np2],axis =1))# horizontal stacking , two array are combined
print(np.concatenate([np1,np2,np3],axis =1))

[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]
[[ 1  2  3  7  8  9 13 14 15 16]
 [ 4  5  6 10 11 12 17 18 19 20]]


In [198]:
np.hstack((np1,np2))

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [210]:
outcome = np.random.randint(1,7, size=10)
outcome

array([4, 3, 4, 5, 5, 6, 3, 6, 4, 3])

In [219]:
x = [99,11,12,34]
a = np.array(x)
-(np.sort(-a))# for dec order

array([99, 34, 12, 11])

In [248]:
np4 = np.concatenate([np1,np2],axis =0)
#print(np.split(np4,2,axis =1))
print(np4)
#print(np.split(np4,2,axis =1)) #3 vertical cbind
#print(np.split(np4,2,axis =0)) # horizontal rbind
#print(np.split(np4,3,axis =1)) error
print(np.split(np4,4,axis =0))
print(np.split(np4,3,axis =1))

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]]), array([[10, 11, 12]])]
[array([[ 1],
       [ 4],
       [ 7],
       [10]]), array([[ 2],
       [ 5],
       [ 8],
       [11]]), array([[ 3],
       [ 6],
       [ 9],
       [12]])]


In [18]:
import pandas as pd
import numpy as np

In [19]:
pandas_series = pd.Series([4, 8, 8.1, -4])
pandas_series

0    4.0
1    8.0
2    8.1
3   -4.0
dtype: float64

In [21]:
pandas_series = pd.Series([4, 8, 8.1, -4], index = ["a", "c", "b", "d"])
pandas_series


a    4.0
c    8.0
b    8.1
d   -4.0
dtype: float64

In [22]:
pandas_series [pandas_series < 5 ]

a    4.0
d   -4.0
dtype: float64

In [255]:
panda_series = pd.Series([["hi","hello"],5.4,-9.4,12],index = ["a","b","c","d"])
panda_series

a    [hi, hello]
b            5.4
c           -9.4
d             12
dtype: object

In [257]:
dictionary = {"a":["hi","Hello"],"b":[5.4,7.5,6.2],"c":-9.4,"d":12}
s=pd.Series(dictionary)
print(s)

a        [hi, Hello]
b    [5.4, 7.5, 6.2]
c               -9.4
d                 12
dtype: object


In [258]:
data = {"date" : [ "December,2014", "December, 2013",
                  "December, 2012","December,2011"],
        "global_temp": [0.87,0.74,0.65,0.63]
       }
dataframe = pd.DataFrame(data)
dataframe

date  global_temp
0   December,2014         0.87
1  December, 2013         0.74
2  December, 2012         0.65
3   December,2011         0.63

In [23]:
dataframe = pd.DataFrame(np.random.randn(20, 5), 
                         columns = ['A', 'B', 'C', 'D', 'E'])
print(dataframe)

           A         B         C         D         E
0  -0.147414 -0.605719  0.423409 -1.248272  0.206845
1  -0.336978 -0.753354 -0.181897 -0.906146  0.139346
2   0.728231  0.905602 -0.227078  0.563114  0.046279
3   0.368426 -0.621809  0.258146 -0.221622  0.277906
4  -2.270256 -0.456044 -0.468874  0.493520 -1.641945
5   0.451211 -0.404953 -0.662455 -1.824985 -0.474828
6   2.622200  2.303293 -1.289547  1.005967 -0.624345
7   2.508804  1.388328  0.088000 -0.302736 -1.701246
8   1.135701  0.463062  0.375979 -0.041291 -0.545029
9   0.126300  2.215378 -1.528780 -1.604008  1.299882
10  1.344268 -0.677013 -1.632476 -0.742362 -0.686505
11  0.449236 -2.153481 -1.077388 -1.680069  0.814123
12  0.600924 -0.119631  1.242032  0.196576 -1.693470
13  0.847054 -0.841528  0.386216  0.981126  0.625309
14 -0.515522  0.915052 -0.091630  0.781453 -0.408705
15 -0.252325  0.509770  0.061860  1.572733 -1.546600
16 -1.138521  1.856105  1.224758 -1.675274 -0.027200
17 -0.653400  1.307954  0.885742 -1.717310  0.

In [261]:
dataframe.head()

A         B         C         D         E
0 -2.248499  0.565953 -0.133768  1.481839  0.555364
1 -0.577268 -0.223668 -1.453036  1.979357  1.063843
2 -0.774609  2.001275  0.169254  1.764348  1.640502
3 -0.054249 -0.371595  0.479161  1.521080 -0.316489
4 -0.983033  0.434969 -1.005276  1.162446 -0.787672

In [262]:
dataframe.tail()

A         B         C         D         E
15 -0.532602 -1.394756 -0.264682  0.120430 -0.659559
16  1.400926 -0.000638 -0.167270 -1.095839  1.043894
17  0.292425 -2.458271  0.549480 -1.399600  1.452660
18 -0.967912  0.042502  0.089244  1.251606 -0.089631
19  0.789295  0.431347 -0.827883  0.390866 -0.507299

In [263]:
dataframe.describe()

A          B          C          D          E
count  20.000000  20.000000  20.000000  20.000000  20.000000
mean   -0.276535   0.078253   0.051060   0.343876   0.109300
std     1.093502   0.993591   0.933918   1.023033   0.907281
min    -2.248499  -2.458271  -1.453036  -1.399600  -1.205272
25%    -1.004232  -0.306056  -0.469925  -0.275934  -0.691587
50%    -0.293425   0.055165  -0.022262   0.157402   0.075617
75%     0.515306   0.591723   0.564234   1.309164   0.953179
max     1.400926   2.001275   2.381133   1.979357   1.640502

In [266]:
dataframe.sort_values(by = 'C' , ascending= False).head()

A         B         C         D         E
9   0.591392 -0.783691  2.381133 -0.392657 -0.279772
8   0.296088  0.669034  1.069388 -0.507201 -0.961408
5   1.020448  0.067828  1.016274  1.776670  0.923470
14 -1.871224 -0.284210  1.001268  0.203392  0.240865
10  1.326561  1.074163  0.608496  0.194374 -1.205272

In [268]:
dataframe.A.head(5)

0   -2.248499
1   -0.577268
2   -0.774609
3   -0.054249
4   -0.983033
Name: A, dtype: float64

In [271]:
dataframe[1:4][['B','C','D']]

B         C         D
1 -0.223668 -1.453036  1.979357
2  2.001275  0.169254  1.764348
3 -0.371595  0.479161  1.521080

In [272]:
# particular rows
dataframe.iloc[[2,3,8,14],[0,1]]

A         B
2  -0.774609  2.001275
3  -0.054249 -0.371595
8   0.296088  0.669034
14 -1.871224 -0.284210

In [276]:
dataframe.iloc[[1,2,3],[0]]

A
1 -0.577268
2 -0.774609
3 -0.054249

In [279]:
dataframe[dataframe.A>0.5][['A','B','C']]

A         B         C
5   1.020448  0.067828  1.016274
9   0.591392 -0.783691  2.381133
10  1.326561  1.074163  0.608496
16  1.400926 -0.000638 -0.167270
19  0.789295  0.431347 -0.827883

In [281]:
df = pd.DataFrame({'group': ['a', 'a', 'b', 'b'],
                   'group_Name': ['Marker', 'Marker', 'Projector', 'Projector'],
                         'value1':[12, 10, 3, 6],
                         'value2':[120, 100, 30, 60]})
df

group group_Name  value1  value2
0     a     Marker      12     120
1     a     Marker      10     100
2     b  Projector       3      30
3     b  Projector       6      60

In [282]:
grouped = df.groupby('group')
print(grouped)

In [283]:
print(grouped.mean())

       value1  value2
group                
a        11.0   110.0
b         4.5    45.0


In [285]:
df. groupby(['group','group_Name']).agg({'value1':np.sum, 'value2':np.mean})

value1  value2
group group_Name                
a     Marker          22     110
b     Projector        9      45

KeyError: 'group'

In [ ]:
import